//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class attendance
    {
        public int attendance_id { get; set; }
        public int student_id { get; set; }
        public int class_id { get; set; }
        public string attendance_attended { get; set; }
        public System.DateTime attendance_date { get; set; }
    
        public virtual classs classs { get; set; }
        public virtual student student { get; set; }
    }
}
