//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBapp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MYDBprojectEntities : DbContext
    {
        public MYDBprojectEntities()
            : base("name=MYDBprojectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<attendance> attendances { get; set; }
        public virtual DbSet<classs> classses { get; set; }
        public virtual DbSet<inventory> inventories { get; set; }
        public virtual DbSet<login> logins { get; set; }
        public virtual DbSet<payment> payments { get; set; }
        public virtual DbSet<rank> ranks { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<student_reg> student_reg { get; set; }
        public virtual DbSet<students_parent> students_parent { get; set; }
    }
}
