//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rank
    {
        public int rank_id { get; set; }
        public int student_id { get; set; }
        public string rank_beltcolor { get; set; }
        public System.DateTime rank_date { get; set; }
    
        public virtual student student { get; set; }
    }
}
