//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class students_parent
    {
        public int students_parent_id { get; set; }
        public string students_parent_mobile { get; set; }
        public string students_parent_email { get; set; }
        public string students_parent_isstudent { get; set; }
        public string students_parent_mothername { get; set; }
        public string students_parent_fathername { get; set; }
        public int student_id { get; set; }
    
        public virtual student student { get; set; }
    }
}
