//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student_reg
    {
        public int student_reg_id { get; set; }
        public int student_id { get; set; }
        public int class_id { get; set; }
        public string student_reg_registered { get; set; }
    
        public virtual classs classs { get; set; }
        public virtual student student { get; set; }
    }
}
